# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm test
  displayName: 'run unit and integration tests'

- script: |
    npm run-script build
  displayName: 'npm build'

- task: CopyFiles@2
  displayName: 'Copy Build Artifacts to Staging Directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/dist/single-page-web-app'
    Contents: |
      *
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureFileCopy@3
  displayName: 'Copy Build Artifacts to Blob Storage'
  inputs:
    sourcePath: '$(Build.ArtifactStagingDirectory)'
    azureSubscription: azure-rm-math-dojo-non-prod-web-ui-principal
    destination: AzureBlob
    storage: 
    containerName: build-artefacts
    copyFilesInParallel: true
    cleanTargetBeforeCopy: true