# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm test
  displayName: 'run unit and integration tests'

- script: |
    npm run-script build
  displayName: 'npm build'

- task: CopyFiles@2
  displayName: 'Copy Build Artifacts to Staging Directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/dist/single-page-web-app'
    Contents: |
      *
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureCLI@2
  displayName: 'Create Container for Build Artefacts in Storage Account'
  inputs:
    azureSubscription: azure-ad-app-math-dojo-ui-pipeline
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
        az storage account create --name mathdojouibuildartefacts$(Build.SourceBranchName) --kind StorageV2 --location uksouth --resource-group math-dojo-hzprod-web-ui
        az storage blob service-properties update --account-name mathdojouibuildartefacts$(Build.SourceBranchName) --static-website --index-document index.html
        az storage container create --name $web

- task: AzureFileCopy@3
  displayName: 'Copy Build Artifacts to Blob Storage'
  inputs:
    sourcePath: '$(Build.ArtifactStagingDirectory)'
    azureSubscription: azure-ad-app-math-dojo-ui-pipeline
    destination: AzureBlob
    storage: 'mathdojouibuildartefacts$(Build.SourceBranchName)'
    containerName: $web
    copyFilesInParallel: true
    cleanTargetBeforeCopy: true

- task: AzureCLI@2
  displayName: 'Show url for stored blob contents'
  inputs:
    azureSubscription: azure-ad-app-math-dojo-ui-pipeline
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
        az storage account show -n mathdojouibuildartefacts$(Build.SourceBranchName) -g math-dojo-hzprod-web-ui --query "primaryEndpoints.web" --output tsv