# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm test
  displayName: 'run unit and integration tests'

- script: |
    npm run-script build
  displayName: 'npm build'

- task: CopyFiles@2
  displayName: 'Copy Build Artifacts to Staging Directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/dist/single-page-web-app'
    Contents: |
      *
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureCLI@2
  displayName: 'Create Container for Build Artefacts in Storage Account'
  inputs:
    azureSubscription: azure-ad-app-math-dojo-ui-pipeline
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
        az --version
        az storage container create --name $(Build.SourceBranchName) --public-access blob

- task: AzureFileCopy@3
  displayName: 'Copy Build Artifacts to Blob Storage'
  inputs:
    sourcePath: '$(Build.ArtifactStagingDirectory)'
    azureSubscription: azure-ad-app-math-dojo-ui-pipeline
    destination: AzureBlob
    storage: mathdojouibuildartefacts
    containerName: '$(Build.SourceBranchName)'
    copyFilesInParallel: true
    cleanTargetBeforeCopy: true